# Generated by Django 5.2.7 on 2025-11-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Produto')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='Preço Negociável')),
                ('category_name', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('vestuario', 'Vestuário'), ('alimentos_bebidas', 'Alimentos e Bebidas'), ('moveis_decoracao', 'Móveis e Decoração'), ('livros_midia', 'Livros e Mídia'), ('esportes_lazer', 'Esportes e Lazer'), ('beleza_cuidados', 'Beleza e Cuidados Pessoais'), ('automoveis_veiculos', 'Automóveis e Veículos'), ('imoveis', 'Imóveis'), ('servicos_profissionais', 'Serviços Profissionais'), ('saude_bem_estar', 'Saúde e Bem-estar'), ('educacao_cursos', 'Educação e Cursos'), ('pets_animais', 'Pets e Animais'), ('ferramentas_construcao', 'Ferramentas e Construção'), ('arte_artesanato', 'Arte e Artesanato'), ('brinquedos_jogos', 'Brinquedos e Jogos'), ('joias_acessorios', 'Jóias e Acessórios'), ('informatica', 'Informática'), ('telefonia', 'Telefonia'), ('eletrodomesticos', 'Eletrodomésticos'), ('outros', 'Outros')], default='outros', max_length=50, verbose_name='Categoria')),
                ('category_slug', models.SlugField(default='outros', editable=False, verbose_name='Slug do Produto')),
                ('is_service', models.BooleanField(default=False, verbose_name='É um Serviço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível para Venda')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário do Produto')),
            ],
        ),
    ]
