# Generated by Django 5.2.7 on 2025-12-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promocao',
            field=models.BooleanField(default=False, verbose_name='Em Promoção'),
        ),
    ]
