# Generated by Django 5.2.7 on 2025-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_promocao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_promocao',
            new_name='is_promotion',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Antigo (Sem desconto)'),
        ),
    ]
