# Generated by Django 5.2.7 on 2025-12-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_is_promocao_product_is_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Contador de Visualizações'),
        ),
    ]
