# Generated by Django 5.2.7 on 2025-10-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('tipo', models.CharField(choices=[('TECH', 'Tecnologia'), ('FOOD', 'Alimentação')], max_length=50)),
                ('categoria', models.CharField(choices=[('PEQ', 'Pequena'), ('MED', 'Média'), ('GRD', 'Grande')], max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_lojas/')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
