# Generated by Django 5.2.7 on 2025-12-08 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Comunidade')),
                ('categoria', models.CharField(choices=[('esportes', 'Esportes'), ('bairro', 'Bairro'), ('musica', 'Música'), ('jogos', 'Jogos'), ('educacao', 'Educação'), ('outros', 'Outros')], default='outros', max_length=50, verbose_name='Categoria da Comunidade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Comunidade')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='comunidades_clientes/capas/', verbose_name='Foto de Capa')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_comunidades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('seguidores', models.ManyToManyField(blank=True, related_name='comunidades_cliente_seguidas', to=settings.AUTH_USER_MODEL, verbose_name='Membros')),
            ],
            options={
                'verbose_name': 'Comunidade de Cliente',
                'verbose_name_plural': 'Comunidades de Clientes',
                'ordering': ['-criada_em'],
            },
        ),
    ]
