# Generated by Django 5.2.7 on 2025-10-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_clientes/')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('interesses', models.CharField(blank=True, choices=[('CON', 'Construção'), ('SAU', 'Saúde'), ('ELE', 'Eletrônicos')], max_length=3, null=True)),
            ],
        ),
    ]
