<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-18 23:19
=======
# Generated by Django 5.2.7 on 2025-10-18 15:27
>>>>>>> dcf8ff9e5f7260a29d806f5a65faa73cf2608609

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
<<<<<<< HEAD
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
=======
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
>>>>>>> dcf8ff9e5f7260a29d806f5a65faa73cf2608609
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('is_lojista', models.BooleanField(default=False)),
                ('is_cliente', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesses', models.CharField(blank=True, choices=[('CON', 'Construção'), ('SAU', 'Saúde'), ('ELE', 'Eletrônicos')], max_length=3, null=True, verbose_name='Interesses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LojistaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='lojistas/profile_pics', verbose_name='Foto de Perfil')),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='lojistas/cover_pics', verbose_name='Foto de Capa')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('company_type', models.CharField(choices=[('TECH', 'Tecnologia'), ('FOOD', 'Alimentação')], max_length=50, verbose_name='Tipo da Empresa')),
                ('company_category', models.CharField(choices=[('ROUP', 'Roupas e Acessórios'), ('ELET', 'Eletrônicos'), ('COSM', 'Cosméticos'), ('REST', 'Restaurantes')], max_length=50, verbose_name='Categoria da Empresa')),
=======
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('company_type', models.CharField(choices=[('TECH', 'Tecnologia'), ('FOOD', 'Alimentação')], max_length=50, verbose_name='Tipo da Empresa')),
                ('company_category', models.CharField(choices=[('PEQ', 'Pequena')], max_length=50, verbose_name='Categoria da Empresa')),
>>>>>>> dcf8ff9e5f7260a29d806f5a65faa73cf2608609
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Empresa')),
                ('operating_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de Funcionamento')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua/Avenida')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lojista_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
