# Generated by Django 5.2.7 on 2025-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pics', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='lojistaprofile',
            name='company_category',
            field=models.CharField(choices=[('ROUP', 'Roupas e Acessórios'), ('ELET', 'Eletrônicos'), ('COSM', 'Cosméticos'), ('REST', 'Restaurantes'), ('Construção', 'Construção'), ('Saúde', 'SAUDE')], max_length=50, verbose_name='Categoria da Empresa'),
        ),
    ]
