# Generated by Django 5.2.7 on 2025-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojistaprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='lojistas/cover_pics', verbose_name='Foto de Capa'),
        ),
        migrations.AddField(
            model_name='lojistaprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='lojistas/profile_pics', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='lojistaprofile',
            name='company_category',
            field=models.CharField(choices=[('ROUP', 'Roupas e Acessórios'), ('ELET', 'Eletrônicos'), ('COSM', 'Cosméticos'), ('REST', 'Restaurantes')], max_length=50, verbose_name='Categoria da Empresa'),
        ),
    ]
