# Generated by Django 5.2.7 on 2025-10-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_clienteprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/profile_pics', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='lojistaprofile',
            name='company_category',
            field=models.CharField(choices=[('ROUP', 'Roupas e Acessórios'), ('ELET', 'Eletrônicos'), ('COSM', 'Cosméticos'), ('REST', 'Restaurantes'), ('Construção', 'Construção'), ('Saúde', 'Sapude')], max_length=50, verbose_name='Categoria da Empresa'),
        ),
    ]
