# Generated by Django 5.2.7 on 2025-10-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_lojistaprofile_cover_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
