# Generated by Django 5.2.7 on 2025-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_clienteprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojistaprofile',
            name='company_category',
            field=models.CharField(choices=[('ROUP', 'Roupas e Acessórios'), ('ELET', 'Eletrônicos'), ('COSM', 'Cosméticos'), ('REST', 'Restaurantes'), ('Construção', 'Construção'), ('Saúde', 'Saúde')], max_length=50, verbose_name='Categoria da Empresa'),
        ),
    ]
