# Generated by Django 5.2.7 on 2025-11-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/clientes/profile_pics', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='lojistaprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/lojistas/cover_pics', verbose_name='Foto de Capa'),
        ),
        migrations.AlterField(
            model_name='lojistaprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/lojistas/profile_pics', verbose_name='Foto de Perfil'),
        ),
    ]
