# Generated by Django 5.2.7 on 2025-11-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_clienteprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/profile_pics', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='lojistaprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='lojistas/cover_pics', verbose_name='Foto de Capa'),
        ),
        migrations.AlterField(
            model_name='lojistaprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='lojistas/profile_pics', verbose_name='Foto de Perfil'),
        ),
    ]
