# Generated by Django 5.2.7 on 2025-11-15 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_alter_user_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lojista_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comunidade', to='user.lojistaprofile')),
                ('membros', models.ManyToManyField(blank=True, related_name='comunidades_participantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='publicacoes/imagens/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='community.comunidade')),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
