# Generated by Django 5.2.7 on 2025-11-16 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('user', '0008_alter_clienteprofile_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_feitos', to=settings.AUTH_USER_MODEL)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='community.publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Comunidade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Comunidade')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('lojista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='user.lojistaprofile', verbose_name='Lojista Responsável')),
                ('seguidores', models.ManyToManyField(blank=True, related_name='comunidades_seguidas', to=settings.AUTH_USER_MODEL, verbose_name='Seguidores da Comunidade')),
            ],
            options={
                'verbose_name': 'Comunidade',
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='comunidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='community.community'),
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='community.publicacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('publicacao', 'usuario')},
            },
        ),
        migrations.DeleteModel(
            name='Comunidade',
        ),
    ]
