# Generated by Django 5.2.7 on 2025-11-29 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_enquete_opcaoenquete_votoenquete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcaoenquete',
            options={'ordering': ['-votos_count']},
        ),
        migrations.RenameField(
            model_name='enquete',
            old_name='encerrada',
            new_name='encerrada_manualmente',
        ),
        migrations.AddField(
            model_name='enquete',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.AddField(
            model_name='opcaoenquete',
            name='votos_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='votoenquete',
            unique_together={('enquete', 'usuario')},
        ),
    ]
