# Generated by Django 5.2.7 on 2025-12-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_enquete_opcaoenquete_votoenquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtida',
            name='user_has_liked',
            field=models.BooleanField(default=True),
        ),
    ]
