# Generated by Django 5.2.7 on 2025-12-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_curtida_user_has_liked'),
        ('customer_community', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='comunidade_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquetes', to='customer_community.clientecommunity'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='comunidade_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='customer_community.clientecommunity'),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquetes', to='community.community'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='community.community'),
        ),
    ]
